services:
  birds:
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    environment:
      ARECORD_DEVICE: plug:mic_in # use the PCM we just defined
      FORCE_ARECORD_DEVICE: "1"
      RECORD_CMD: python -u record/record_upload.py
